apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: apache-hpd
  namespace: autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics: 
  - type: Resource
    resouce: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300