apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    type: Calico
  calicoNetwork:
    bgp: disabled
    ipPools:
      - cidr: 192.168.0.0/16
        natOutGoing: Enabled
        nodeSelector: all()